### PR TITLE
chore(upload-csv): Implemented upload of csv file

### PR DESCRIPTION
**Pull request by nnamdi16**

### CODE REVIEW

**Review by luis11011 — COMMENTED** [review]
Thank you, this helps a lot!

This is great but not only CSV files should be allowed.

Csv, xml, json, excel, avro, parquet, orc, zip, hdf5 are the type of files Optimus supports. Also, the extension `txt` should be included since there are cases comma separated value files have this format.

Also it seems you pushed unneccessary changes to the local libraries in `yarn.lock`. That can be removed.

**Comment by nnamdi16** [comment]
I would add all the file extensions you listed and remove the unnecessary dependencies added to yarnlock

**Comment by nnamdi16** [comment]
I would add all the file extensions you listed and remove the unnecessary dependencies added to yarnlock

**Comment by nnamdi16** [comment]
I have updated the PR. Please review @luis11011

**Comment by luis11011** [comment]
Just pushed an update after checking the code locally, your changes would cause an incompatibility with presigned urls from external services.

**Comment by nnamdi16** [comment]
> Just pushed an update after checking the code locally, your changes would cause an incompatibility with presigned urls from external services.

What is the format for the presigned url

**Pull request closed without merging**
